### ISSUE TITLE
Implement build-process for "core" and "task-manager" packages

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/fsm-workflow#10]
- [x] Add [npm-scripts](https://www.npmjs.com/package/@opuscapita/npm-scripts) (#11)
- [x] Add changelog generation (#11)
- [x] Build sources to bundles (#11)
- [x] Publish bundles to public [npmjs.com](npmjs.com) (#11)
- [ ] Implement scripts to release multi-package repos

**Comment by asergeev-sc** [comment]
FSM core and task-manager are pure not web JS libraries, so we don't need webpack here, please process original JS files with babel to get ES5 code and that is it.

**Comment by asergeev-sc** [comment]
The last point from list will be done inside #36
